### ISSUE TITLE
Upload SBOM should not require "location". Only the file itself should be required

### ISSUE THREAD

**Issue by carlosthe19916** [trustification/trustify#294] opened 2024-05-15 12:25 UTC
Only the SBOM (file) itself should be required while uploading it to the server, any other info should be determined by the server itself.

![Screenshot from 2024-05-15 14-23-24](https://github.com/trustification/trustify/assets/2582866/4a945eed-e88e-4496-9e57-33bf0a810860)

**Comment by ctron** [comment] 2024-05-16 07:32
Until we really decided on how to proceed with the "location" information I think we should keep it as is.

That API may be used by the UI, but also from other application (CLI, other applications). In such a case, there should be the ability to provide the information. Having two endpoints, one for the UI, and one for the "others", doesn't make sense to me.

In the case of the UI it might be reasonable to just provide a constant value for now (`manual`, `user`, `ui`, …)

**Comment by carlosthe19916** [comment] 2024-05-16 08:14
> Until we really decided on how to proceed with the "location" information I think we should keep it as is.

Let's use this Github Issue to decide how to proceed then.

> That API may be used by the UI, but also from other application (CLI, other applications). In such a case, there should be the ability to provide the information. Having two endpoints, one for the UI, and one for the "others", doesn't make sense to me.

- I agree, we should not have 2 endpoints that serve the same purpose.

> In the case of the UI it might be reasonable to just provide a constant value for now (`manual`, `user`, `ui`, …)

I don't think that is reasonable. If there is a constant to be set, the constant should be set in the server and not in the client. E.g. The constant can be set in the definition of the REST endpoint itself with something like `location=rest`.

In the worst case scenario, if we decide to keep the "location" being set in the REST endpoint, then that should be an optional parameter. The only required data should be the SBOM file itself.

**Comment by ctron** [comment] 2024-05-16 08:31
How would the server side know if the request originated by the UI or another application?

**Comment by carlosthe19916** [comment] 2024-05-16 08:58
> How would the server side know if the request originated by the UI or another application?

- Why the server need to know where the request was originated? 
- If we have a real requirement of "being able to know where the request was originated" then the current "location" param does not solve it and we need to think in a real solution.
  - The UI can set a constant `location=ui`. Fine
  - I can execute a CURL command in my terminal and set `location=ui`. Not fine. the request was originated in my terminal but the server will assume it was originated in the UI.
  - A third party application can set `location=ui`. Not fine. The request was originated outside the realm of our app and yet the server will assume it was generated by our UI.

So what problem are we solving with "location" being set in through the API? 

I could set the "location" as a constant in the UI. But in favor or having a good API design let's take our time to evaluate  how to proceed with "location". I'd also like to know what the other team members think about "location" and whether or not we are doing it right

**Comment by carlosthe19916** [comment] 2024-05-16 13:02
The original statement was `How would the server side know if the request originated by the UI or another application?`. And I gave an example explaining why "location" does not solve the problem of "knowing where the request was originated"

> It's not about the request, but the source of the file. Right now, when using importers, that field is filled with that source. Assume two sources provide the same file. How would we handle this?

Now, it it is not about the "request" but about the "source of the file". 

Looking at some of the tests under the repository I can see "location" being used as "who created the file". In the code below, `location=http://redhat.com/` which suggest that "location" defines "who" is the "author|owner|source of the file"

https://github.com/trustification/trustify/blob/fabcbb8f41ff15af6a3666a7d691df1e2c18360d/modules/advisory/src/service/test.rs#L24-L38

The problem of exposing "location" in the REST API is that I can upload any file using my CURL command and set `location=http://redhat.com/` in my POST request (there is nothing that prevents me to do so). Doing it, I have just allocated a FALSE ownership of a file to "http://redhat.com/".

> I think having a simple field carrying the information where the file originated from makes sense.
> 
> But maybe you have a better way to solve issues around that topic.

I don't like the idea exposing that field through the REST API; moreover, forcing clients to define a "location" opens the possibility of allocating false "locations|source" to files, just as I explained in my example above.

- As far as I know (keep me right on this). The importers are not hitting the REST endpoints for populating the DB therefore the importers do not care whether or not the "location" is exposed through the REST endpoints.
- The best guess about "location|source" of a file being uploaded through the REST API is that "location=rest-endpoint" we can not know the real origin or the file. So setting `location=rest-endpoint`, as a constant, in the Backend is the best we can do.

My comments might be wrong because i think I do not have a clear definition of "location". Thinking carefully, the current usage of "location" seems just as a "label" (a random string that can be assigned to a file) adding labels to files|sboms sounds better than "location".

I have the feeling that setting the constant in the UI or Backend will be just a workaround, the real problem is to define what "location" means and how it is used in the app.

**Comment by jcrossley3** [comment] 2024-05-17 15:43
Just another data point, but I removed the required location param from the advisory upload and [replaced it with a hard-coded "rest-api" tag](https://github.com/trustification/trustify/blob/f2104f355237e28e5f10308d55f9648558a2009e/modules/ingestor/src/endpoints/advisory.rs#L32), which seems silly to me. But maybe it (or some other tag) is appropriate if all the other importers use the base-url of whatever site they're getting their docs from. If so, can I do the same for the sbom upload?

One other data point: issuer and location seem very similar to me, so much so that I created #273

**Comment by ctron** [comment] 2024-05-17 16:24
I think it would make sense to have a strategy. Vs doing random stuff to please a single spot in the code/api.

Me feeling is that we need labels on the documents: https://github.com/trustification/trustify/discussions/193

**Comment by ctron** [comment] 2024-06-21 11:45
Isn't this a duplicate of https://github.com/trustification/trustify/issues/273?

**Comment by jcrossley3** [comment] 2024-06-21 13:22
> Isn't this a duplicate of #273?

I think so. I think the labels feature covers it.

**Comment by carlosthe19916** [comment] 2024-06-26 08:29
@ctron @jcrossley3 if this is a duplicate and https://github.com/trustification/trustify/issues/273 has been solved already I was expecting this title of this issue was covered already.

The latest commit in the main branch still requires the location in the Upload SBOM REST endpoint. Am I missing something?

![Screenshot from 2024-06-26 10-27-22](https://github.com/trustification/trustify/assets/2582866/a8d8163d-d57b-4f3d-afe4-b4ee494ebcee)

**Comment by ctron** [comment] 2024-06-26 08:32
Ah yes, we're still missing an update of the API. We need to find a good way to hand over the `Map<String,String>` to the backend.

**Comment by ctron** [comment] 2024-07-01 11:34
PR https://github.com/trustification/trustify/pull/475 allows setting the label once the file is uploaded.

**Closed** 2024-07-03 07:56 UTC
Labels: frontend
