### ISSUE TITLE
PM mode doesn't work

### ISSUE THREAD

**Issue by ctron** [trustification/trustify#225] opened 2024-05-02 11:59 UTC
The README suggests to start it up with:

> `cargo run --bin trustd`

That results in:

```
2024-05-02T11:55:09.124060Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-02T11:55:09.237346Z  INFO trustd::db: PostgreSQL installed in "/home/jreimann/git/trustify/.trustify/postgres"    
2024-05-02T11:55:09.237389Z  INFO trustd::db: Running on port 36325    
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 36325 failed: could not initiate GSSAPI security context: Unspecified GSS failure.  Minor code may provide more information: Ticket expired
connection to server at "localhost" (::1), port 36325 failed: FATAL:  password authentication failed for user "postgres"
```

@carlosthe19916 seems to have the same issue: https://github.com/trustification/trustify/pull/224#pullrequestreview-2035429356

**Comment by helio-frota** [comment] 2024-05-03 11:55
note: I think we can close that probably was just the thing with `.trustify` directory right?
https://github.com/trustification/trustify/pull/226#issuecomment-2090437410

**Comment by helio-frota** [comment] 2024-05-03 12:27
> note: I think we can close that probably was just the thing with .trustify directory right?

not it isn't ... 

Jim wrote: `I'm wondering if there may be a race condition somewhere.`

I did a good amount of different sequences , downgrading to 0.6, removing the dir, running the app, upgrading to 0.9 , running the app, removing the dir etc etc .. not able to reproduce the problem...

**Comment by jcrossley3** [comment] 2024-05-03 12:34
It happened to me yesterday. It seemed to be in a state where the error would repeat until I deleted `.trustify/`
```
[jim@fedora trustify]$ cargo run --bin trustd
   Compiling trustify-module-search v0.1.0 (/home/jim/src/trustification/trustify/modules/search)
   Compiling trustify-module-ingestor v0.1.0 (/home/jim/src/trustification/trustify/modules/ingestor)
   Compiling trustify-module-fetch v0.1.0 (/home/jim/src/trustification/trustify/modules/fetch)
   Compiling trustify-module-importer v0.1.0 (/home/jim/src/trustification/trustify/modules/importer)
   Compiling trustify-server v0.1.0 (/home/jim/src/trustification/trustify/server)
   Compiling trustify-trustd v0.1.0 (/home/jim/src/trustification/trustify/trustd)
    Finished dev [unoptimized + debuginfo] target(s) in 19.46s
     Running `target/debug/trustd`
2024-05-03T00:27:19.966971Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-03T00:27:20.072049Z  INFO trustd::db: PostgreSQL installed in "/home/jim/src/trustification/trustify/.trustify/postgres"    
2024-05-03T00:27:20.072130Z  INFO trustd::db: Running on port 45235    
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 45235 failed: FATAL:  password authentication failed for user "postgres"

[jim@fedora trustify]$ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/trustd`
2024-05-03T00:27:45.186626Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-03T00:27:45.291581Z  INFO trustd::db: PostgreSQL installed in "/home/jim/src/trustification/trustify/.trustify/postgres"    
2024-05-03T00:27:45.291711Z  INFO trustd::db: Running on port 43947    
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 43947 failed: FATAL:  password authentication failed for user "postgres"

[jim@fedora trustify]$ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/trustd`
2024-05-03T00:27:55.822048Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-03T00:27:55.927022Z  INFO trustd::db: PostgreSQL installed in "/home/jim/src/trustification/trustify/.trustify/postgres"    
2024-05-03T00:27:55.927105Z  INFO trustd::db: Running on port 45925    
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 45925 failed: FATAL:  password authentication failed for user "postgres"

[jim@fedora trustify]$ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/trustd`
2024-05-03T00:27:58.354032Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-03T00:27:58.458906Z  INFO trustd::db: PostgreSQL installed in "/home/jim/src/trustification/trustify/.trustify/postgres"    
2024-05-03T00:27:58.458985Z  INFO trustd::db: Running on port 36155    
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 36155 failed: FATAL:  password authentication failed for user "postgres"

[jim@fedora trustify]$ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/trustd`
2024-05-03T00:28:02.094955Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-03T00:28:02.199894Z  INFO trustd::db: PostgreSQL installed in "/home/jim/src/trustification/trustify/.trustify/postgres"    
2024-05-03T00:28:02.199985Z  INFO trustd::db: Running on port 36951    
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 36951 failed: FATAL:  password authentication failed for user "postgres"

[jim@fedora trustify]$ rm -rf .trustify/
[jim@fedora trustify]$ cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/trustd`
2024-05-03T00:28:09.138933Z  WARN trustd::db: Setting up managed DB; not suitable for production use!    
2024-05-03T00:28:16.209271Z  INFO trustd::db: PostgreSQL installed in "/home/jim/src/trustification/trustify/.trustify/postgres"    
2024-05-03T00:28:16.209364Z  INFO trustd::db: Running on port 43393    
2024-05-03T00:28:16.236546Z  INFO bootstrap: sqlx::postgres::notice: database "trustify" does not exist, skipping database=Database { username: "postgres", password: "postgres", host: "localhost", port: 43393, name: "trustify" }
2024-05-03T00:28:16.237259Z  INFO bootstrap: sqlx::query: summary="DROP DATABASE IF EXISTS …" db.statement="\n\nDROP DATABASE IF EXISTS \"trustify\";\n" rows_affected=0 rows_returned=0 elapsed=722.36µs elapsed_secs=0.00072236 database=Database { username: "postgres", password: "postgres", host: "localhost", port: 43393, name: "trustify" }
2024-05-03T00:28:16.263187Z  INFO bootstrap: sqlx::query: summary="CREATE DATABASE \"trustify\";" db.statement="" rows_affected=0 rows_returned=0 elapsed=16.242361ms elapsed_secs=0.016242361 database=Database { username: "postgres", password: "postgres", host: "localhost", port: 43393, name: "trustify" }
```
When it happens again, I'll try to debug it more carefully.

**Comment by jcrossley3** [comment] 2024-05-03 19:35
Now I'm starting to wonder if the only times that PM mode hasn't worked for us is when something changed about the auth to the database, e.g. after the update to 0.9.1, so when you pulled those changes from the repo, the auth didn't match your current postgres install, so you *had* to blow away `.trustify/` in order to get the db's creds in sync with the code's creds.

**Comment by helio-frota** [comment] 2024-05-03 20:02
:man_shrugging:  I got it minutes ago while making an experiment with this tool I found: https://github.com/kurotych/sqlant 
( trying to generate the diagram etc...without success.. )
```
➜  ~ sqlant postgresql://postgres:trustify@localhost:5432/trustify
thread 'main' panicked at /home/heliofrota/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlant-0.3.1/src/main.rs:55:6:
called `Result::unwrap()` on an `Err` value: Postgres(Error { kind: Connect, cause: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

![2024-05-03_16-59](https://github.com/trustification/trustify/assets/6443576/953c9aaf-22b6-4e7d-8a0c-274f4bcc799d)

**Comment by helio-frota** [comment] 2024-05-03 20:05
:thinking: something is wrong with this hour in the screenshot 
`2024-05-03T19:56:05.954025Z`

right now is 17:04 here

![2024-05-03_17-04](https://github.com/trustification/trustify/assets/6443576/38c6602c-ba30-43d6-ab70-120ab52b78e9)

**Comment by jcrossley3** [comment] 2024-05-03 21:08
Yes, but could that be explained by today's revert of the postgres password? If you created the database beneath `.trustify/` with one password, and then pulled down another after the revert, you'll need to blow away `.trustify/` to force a re-install with that change.

**Comment by helio-frota** [comment] 2024-05-03 21:11
probably :+1:

**Comment by helio-frota** [comment] 2024-05-06 17:40
> but could that be explained by today's revert of the postgres password? If you created the database beneath .trustify/ with one password, and then pulled down another after the revert, you'll need to blow away .trustify/ to force a re-install with that change.

Yes, confirmed. And this behavior also works when using `env_vars`:

```console
➜  trustify git:(main) ✗ DB_PASSWORD=1234 cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/trustd`
2024-05-06T17:38:24.389679Z  WARN trustd::db: Setting up managed DB; not suitable for production use!
2024-05-06T17:38:24.496839Z  INFO trustd::db: PostgreSQL installed in "/home/heliofrota/Desktop/tc/trustify/.trustify/postgres"
2024-05-06T17:38:24.496937Z  INFO trustd::db: Running on port 36669
Error: Command error: stdout=; stderr=psql: error: connection to server at "localhost" (::1), port 36669 failed: FATAL:  password authentication failed for user "postgres"

➜  trustify git:(main) ✗ DB_PASSWORD=trustify cargo run --bin trustd
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/trustd`
2024-05-06T17:38:40.388161Z  WARN trustd::db: Setting up managed DB; not suitable for production use!
2024-05-06T17:38:40.495172Z  INFO trustd::db: PostgreSQL installed in "/home/heliofrota/Desktop/tc/trustify/.trustify/postgres"
2024-05-06T17:38:40.495235Z  INFO trustd::db: Running on port 35781
2024-05-06T17:38:40.513727Z  INFO trustify_common::db: connect to postgres://postgres:trustify@localhost:35781/trustify
```

**Comment by jcrossley3** [comment] 2024-05-06 19:07
I think it's working as designed. I think we can close this.

**Comment by helio-frota** [comment] 2024-05-07 13:38
@jcrossley3 I agree @ctron can we close this ? thanks

extra: a common solution is to delete the directory programmatically but we lost all the data loosing the meaning/design of a pm-mode app.

**Comment by jcrossley3** [comment] 2024-05-09 14:53
Closing for now. Re-open when steps to reproduce emerge.

**Closed by jcrossley3** 2024-05-09 14:53 UTC
Labels: bug
